version: '3.8'

services:
  indigo:
    image: "epmlsop/indigo-service:latest"
    expose:
      - 80
  nginx:
    build:
      context: .
      dockerfile: DOCKERFILE
      args:
        REACT_APP_API_HOST: "http://draw.engchem.ru:63212/api/v2/"
    ports:
      - "6380:80"
    depends_on:
      - indigo
