FROM node:20.7.0-alpine as builder
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

ARG REACT_APP_API_HOST
ENV REACT_APP_API_HOST $REACT_APP_API_HOST

ARG REACT_APP_TARGET_ORIGIN
ENV REACT_APP_TARGET_ORIGIN $REACT_APP_TARGET_ORIGIN

COPY package.json ./
COPY package-lock.json ./
RUN npm ci --silent
RUN npm install react-scripts@3.4.1 -g --silent
COPY . ./
RUN npm run build

FROM nginx:latest
LABEL authors="borisalekseev"

COPY --from=builder /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
