version: '3.8'

services:
  indigo:
    image: "epmlsop/indigo-service:latest"
    expose:
      - 80
  nginx:
    build:
      context: .
      dockerfile: DOCKERFILE
      args:
        REACT_APP_API_HOST: "https://draw.engchem.ru/api/v2/"
    volumes:
      - /certs/server.crt:/home/ubuntu/certs/server.crt:ro
      - /certs/server.key:/home/ubuntu/certs/server.key:ro
    ports:
      - "6380:80"
      - "63443:443"
    depends_on:
      - indigo
