version: '3.8'

services:
  indigo:
    image: "epmlsop/indigo-service:latest"
    expose:
      - 80
  nginx:
    build:
      context: .
      dockerfile: DOCKERFILE
    ports:
      - "6321:80"
    depends_on:
      - indigo
